import type { Metadata } from "next";
import { MarketingNav, MarketingFooter, PageHeader } from "@/components/marketing/Shell";

export const metadata: Metadata = {
  title: "Terms of Service | APEX AERA",
  description: "The terms that govern use of the APEX AERA platform.",
};

const CONTACT_EMAIL = "guardian.v.artemis@gmail.com";
const EFFECTIVE = "September 2, 2026";

const SECTIONS: { title: string; body: string[] }[] = [
  {
    title: "The service",
    body: [
      "APEX AERA is an AI marketing platform that analyzes the content you upload, researches your market, writes platform specific captions, schedules posts, publishes them to social accounts you connect, and reports on the results. Access is by invitation and each client operates inside a private workspace.",
    ],
  },
  {
    title: "Your account",
    body: [
      "You are responsible for keeping your sign in details private and for everything that happens under your account. Tell us right away if you believe your account has been accessed without permission. You must be at least 18 and authorized to act for the brand you represent.",
    ],
  },
  {
    title: "Your content",
    body: [
      "You keep ownership of everything you upload. You give us permission to store, analyze, transform, and publish that content on your behalf, only as needed to provide the service and only to the platforms and accounts you connect. You are responsible for having the rights to the content you upload and for making sure it complies with the rules of each platform it is published to.",
      "Because the platform runs on autopilot by default, content may be captioned, scheduled, and published without a manual review step. You can switch any workspace to manual approval, pull any post from the queue before it publishes, and disconnect any platform at any time.",
    ],
  },
  {
    title: "Connected platforms",
    body: [
      "When you connect a social account you authorize us to publish to it and read basic performance data from it. Your use of those platforms remains subject to their own terms. We are not responsible for a platform rejecting, removing, or limiting the reach of content, or for changes a platform makes to its rules or APIs.",
    ],
  },
  {
    title: "AI generated output",
    body: [
      "Captions, briefs, reports, and funnel drafts are generated by AI from your content, your brand profile, and live research. We work hard to keep them accurate and on brand, but you should review anything that matters and you are responsible for what is published under your name. Reports are built only from real activity in your account and never contain invented metrics.",
    ],
  },
  {
    title: "Acceptable use",
    body: [
      "Do not use the platform to publish content that is unlawful, deceptive, infringing, hateful, or that violates the rules of the platform it is posted to. Do not attempt to access another client's workspace, interfere with the service, or reverse engineer it. We may suspend or close accounts that break these rules.",
    ],
  },
  {
    title: "Fees and termination",
    body: [
      "Fees, billing, and service scope are set out in your service agreement with APEX. Either party may end the relationship as described in that agreement. When a workspace is closed we remove connected platform tokens and, on request, delete your content and data as described in our Privacy Policy.",
    ],
  },
  {
    title: "Disclaimers and liability",
    body: [
      "The service is provided as is. We do not guarantee specific marketing results, reach, or revenue. To the fullest extent allowed by law, APEX is not liable for indirect or consequential losses, and our total liability for any claim is limited to the fees you paid us in the three months before the claim arose.",
    ],
  },
  {
    title: "Changes and contact",
    body: [
      "We may update these terms as the platform evolves. We will update the effective date above and notify you inside the platform of meaningful changes. Continued use after a change means you accept the updated terms. Questions can be sent to " + CONTACT_EMAIL + ".",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen" style={{ background: "var(--bg-deep, #0c0c0c)", color: "var(--text, #e8e8e8)" }}>
      <MarketingNav />
      <PageHeader kicker="Legal" title="Terms of Service" sub={"Effective " + EFFECTIVE} />
      <section className="mx-auto max-w-3xl px-5 sm:px-6 pb-20 pt-2">
        <div className="mkt-card mkt-quiet p-6 sm:p-10 flex flex-col gap-8">
          {SECTIONS.map((s) => (
            <div key={s.title}>
              <h2 className="font-semibold text-base mb-3" style={{ color: "var(--text-2, #d8d8d8)" }}>
                {s.title}
              </h2>
              {s.body.map((p, i) => (
                <p key={i} className="text-sm leading-relaxed mb-3" style={{ color: "var(--text-4, #9a9a9a)" }}>
                  {p}
                </p>
              ))}
            </div>
          ))}
        </div>
      </section>
      <MarketingFooter />
    </main>
  );
}
